### Register user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "1234"
}

### Login user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "1234"
}
### Add expense
POST http://localhost:5000/expense/add
Content-Type: application/json

{
  "title": "Lunch",
  "amount": 150,
  "category": "Food"
}

### Get all expenses
GET http://localhost:5000/expense/all
